In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import defaultdict
import codecs, json
import unicodedata
# pip install Unidecode  <OR> conda install Unidecode
import unidecode

In [15]:
#importing all csv files
domarar = pd.read_csv('csv/blak-domarar.csv', sep=';', header=0)
einstaklingar = pd.read_csv('csv/blak-einstaklingar.csv', sep=';', header=0)
forsvarsmenn = pd.read_csv('csv/blak-forsvarsmenn.csv', sep=';', header=0)
lid = pd.read_csv('csv/blak-lid.csv', sep=';', header=0)
lidimoti = pd.read_csv('csv/blak-lidimoti.csv', sep=';', header=0)
lidsmenn = pd.read_csv('csv/blak-lidsmenn.csv', sep=';', header=0)
lidsstjorar = pd.read_csv('csv/blak-lidsstjorar.csv', sep=';', header=0)
thjalfarar = pd.read_csv('csv/blak-thjalfarar.csv', sep=';', header=0)
mot = pd.read_csv('csv/blak-mot.csv', sep=';', header=0)

# drop all SyndarLids with an ID (SyndarlidID)
# (the reason for not dropping using SyndarLid is because I don't trust that column to be inserted correctly with [0,1])
lid = lid[lid['SyndarlidID'].isna()]
# then dropping those two columns because we don't want virtual teams
lid = lid.drop(columns=['SyndarLid', 'SyndarlidID'])

# All duplicated birthdays
duplicated_einstaklingar = einstaklingar[einstaklingar.duplicated(subset=['Nafn', 'Fdagur', 'Kyn'], keep=False)]
duplicated_fdagur_kyn_einstaklingar = einstaklingar[einstaklingar.duplicated(subset=['Fdagur', 'Kyn'], keep=False)]


In [30]:
duplicate_dict = defaultdict(dict)

for index, row in duplicated_fdagur_kyn_einstaklingar.iterrows():
    full_name = row['Nafn']
    first_name = full_name.split()[0]
    first_name_lowercase = first_name.lower()
    first_name_to_english = unidecode.unidecode(first_name_lowercase)
    Fdagur_date = row['Fdagur'].split()[0]
    
    if first_name_to_english in duplicate_dict.keys():
        if Fdagur_date in duplicate_dict[first_name_to_english].keys():
            duplicate_dict[first_name_to_english][Fdagur_date].append(row.values)
        else:
            duplicate_dict[first_name_to_english][Fdagur_date] = [row.values]
    else:
        #if Fdagur does not exist ->
        duplicate_dict[first_name_to_english][Fdagur_date] = [row.values]
        

In [102]:
#dict(duplicated_fdagur_kyn_einstaklingar)

# all duplicates
#duplicate_dict

# all duplicates for lúðvík
duplicate_dict["ludvik"]

#duplicate_dict["ludvik"]['1969-03-31'][0]
#duplicate_dict["ludvik"]['1969-03-31'][1]

{'1969-03-31': [array([641, 'Lúðvik Kristinsson', '1969-03-31 00:00:00.000', 'kk ',
         'Völsungur', nan, nan, nan, nan, nan, nan, nan,
         '2000-04-04 08:24:44.110', 0.0], dtype=object),
  array([866, 'Lúðvík Kristinsson', '1969-03-31 00:00:00.000', 'kk ', nan,
         nan, nan, nan, nan, nan, nan, nan, '2001-04-17 12:12:41.047', nan],
        dtype=object),
  array([2299, 'Lúðvík Kristinsson', '1969-03-31 00:00:00.000', 'kk ', nan,
         nan, nan, nan, nan, nan, nan, nan, '2007-04-26 11:38:05.860', nan],
        dtype=object)],
 '1996-09-02': [array([4160, 'Lúðvík', '1996-09-02 00:00:00.000', 'kk ', nan, nan, nan,
         nan, nan, nan, nan, nan, '2013-04-28 10:50:35.960', 0.0],
        dtype=object),
  array([4167, 'Lúðvík Már Matthíasson', '1996-09-02 00:00:00.000', 'kk ',
         'HK', nan, nan, nan, nan, nan, nan, nan, '2013-09-03 21:00:29.950',
         0.0], dtype=object)]}

In [104]:
dict_duplicate_compare_team_members = defaultdict(dict)

for index, row in lidsmenn.iterrows():
    ids = row["EinstID"]
    if ids in duplicated_fdagur_kyn_einstaklingar["EinstID"]:
        # now we only view ids that exist for duplicated people
        if ids in dict_duplicate_compare_team_members.keys():
            dict_duplicate_compare_team_members[ids].append(row.values)
        else:
            dict_duplicate_compare_team_members[ids] = [row.values]


In [105]:
#dict_duplicate_compare_team_members

In [129]:
dict_removed_single_entries = defaultdict(dict)

for key, value in duplicate_dict.items():
    temp_dict = dict(value)
    for dict_key, dict_value in temp_dict.items():
        #print("xxxxxxxxxxxxx")
        dict_len = len(dict_value)
        if(dict_len > 1):
            dict_removed_single_entries[key] = value

In [130]:
dict_removed_single_entries

defaultdict(dict,
            {'adalsteinn': [{'1981-03-03': [array([1964, 'Aðalsteinn Eymundsson', '1981-03-03 00:00:00.000', 'kk ',
                       nan, nan, nan, nan, nan, '8212554', nan, nan,
                       '2006-01-09 20:31:04.420', nan], dtype=object),
                array([1437, 'Aðalsteinn Eymundsson', '1981-03-03 00:00:00.000', 'kk ',
                       'HK', 'adalste@hi.is', nan, nan, nan, '6182554', nan, nan,
                       '2003-10-11 19:12:00.827', 0.0], dtype=object)]}],
             'aldis': [{'1996-06-22': [array([2949, 'aldís anna höskuldsdóttir', '1996-06-22 00:00:00.000',
                       'kvk', 'K.A.', 'aldis_anna@hotmail.com', nan, nan, nan, '8681980',
                       '4611143', nan, '2010-02-25 13:52:40.360', 169.0], dtype=object),
                array([2950, 'aldís anna höskuldsdóttir', '1996-06-22 00:00:00.000',
                       'kvk', 'K.A.', 'aldis_anna@hotmail.com', nan, nan, nan, '8681980',
                    

In [131]:
duplicate_dict

defaultdict(dict,
            {'adalbjorn': {'1990-01-01': [array([2930, 'Aðalbjörn Hannesson', '1990-01-01 00:00:00.000', 'kk ', nan,
                      '26aha@ma.is', nan, nan, nan, '6916456', nan, nan,
                      '2010-02-19 17:24:51.373', nan], dtype=object)]},
             'adalheidur': {'1964-03-04': [array([60, 'Aðalheiður Ásmunds', '1964-03-04 00:00:00.000', 'kvk', 'HK',
                      'alla@frodi.is', nan, nan, nan, '8963021', nan, nan,
                      '2000-04-28 15:00:23.000', 0.0], dtype=object)],
              '1973-10-20': [array([1400, 'Aðalheiður Sigursveinsdóttir', '1973-10-20 00:00:00.000',
                      'kvk', 'HK', 'asigursveins@hotmail.com', nan, nan, nan, '7707222',
                      '554-7222', nan, '2003-04-14 22:57:08.747', 0.0], dtype=object)],
              '1968-05-15': [array([1348, 'Aðalheiður Stefánsdóttir', '1968-05-15 00:00:00.000', 'kvk',
                      nan, nan, nan, nan, nan, nan, nan, nan, '2003-03-31 22

In [21]:
reverted_back_to_dict = dict(duplicate_dict)
#reverted_back_to_dict

In [23]:
file_path = "json/einstaklingar_map.txt" ## your path variable
#duplicate_dict_json = json.dump(duplicate_dict, codecs.open(file_path, 'w', encoding='utf-8'), separators=(';', ':'), sort_keys=True, indent=4) ### this saves the array in .json format
#json_obj = json.dumps(duplicate_dict, indent = 4)
#dumped = json.dumps(duplicate_dict, cls=NumpyEncoder)
#dumped
#pd.DataFrame(reverted_back_to_dict).to_csv(file_path, encoding='utf-8-sig')
#duplicate_dict_json = json.dump(reverted_back_to_dict, codecs.open(file_path, 'w', encoding='utf-8-sig'))

#json = json.dumps(reverted_back_to_dict)
#f = open(file_path,"w")
#f.write(str(reverted_back_to_dict))
#f.close()

=====================================================================================
=

In [187]:
#FINAL STEP (run after everything is done):

#duplicated people put into it's own csv to be browsed later
pd.DataFrame(duplicated_einstaklingar).to_csv("csv/new/duplicated-einstaklingar.csv", encoding='utf-8-sig')
pd.DataFrame(duplicate_dict).to_csv("json/duplicate-map.json", encoding='utf-8-sig')


#save as new csv inside csv/new
pd.DataFrame(domarar).to_csv("csv/new/blak-domarar.csv", encoding='utf-8-sig')
pd.DataFrame(einstaklingar).to_csv("csv/new/blak-einstaklingar.csv", encoding='utf-8-sig')
pd.DataFrame(forsvarsmenn).to_csv("csv/new/blak-forsvarsmenn.csv.csv", encoding='utf-8-sig')
pd.DataFrame(lid).to_csv("csv/new/blak-lid.csv", encoding='utf-8-sig')
pd.DataFrame(lidimoti).to_csv("csv/new/blak-lidimoti.csv", encoding='utf-8-sig')
pd.DataFrame(lidsmenn).to_csv("csv/new/blak-lidsmenn.csv", encoding='utf-8-sig')
pd.DataFrame(lidsstjorar).to_csv("csv/new/blak-lidsstjorar.csv", encoding='utf-8-sig')
pd.DataFrame(mot).to_csv("csv/new/blak-mot.csv", encoding='utf-8-sig')
pd.DataFrame(thjalfarar).to_csv("csv/new/blak-thjalfarar.csv", encoding='utf-8-sig')